DATA:
  DATASET: rareplanes-real
  IMG_SIZE: 384
  NUM_WORKERS: 0
MODEL:
  TYPE: swin
  NAME: swin_base_patch4_window12_384_rareplanes_synth_to_real_visusualize
  SOURCE_NUM_CLASSES: 1000
  NUM_CLASSES: 3
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 12
TEST:
  CROP: False
