DATA:
  DATASET: food-101
  IMG_SIZE: 384
  NUM_WORKERS: 20
MODEL:
  TYPE: swin
  NAME: swin_base_patch4_window12_384_22ktofood101_transfer
  DROP_PATH_RATE: 0.2
  SOURCE_NUM_CLASSES: 1000
  NUM_CLASSES: 101
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 12
TRAIN:
  EPOCHS: 30
  WARMUP_EPOCHS: 3
  WEIGHT_DECAY: 1e-8
  BASE_LR: 2e-04
  WARMUP_LR: 2e-07
  MIN_LR: 2e-06